import "css/Global.scss"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from 'layout/Navigation/Navigation'
import navigation from 'data/navigation'
import logoImage from "assets/mechanik-ludomy-logo.webp";
import LayoutProvider from "context/LayoutContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LayoutProvider>
        <body className={inter.className}>
          <Navigation
            brand={{
              label:navigation.brand.label,
              image:{
                altText:"",
                sourceUrl:logoImage,
                title:""
              },
              uri:navigation.brand.uri
            }}
            location={navigation.location}
            menu={navigation.menu}
            settings={navigation.settings}
          />
          {children}
        </body>
      </LayoutProvider>
    </html>
  )
}
